version: "3.9"

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: control2_db
    environment:
      POSTGRES_DB: control2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d control2"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./gestion-tareas-backend
    container_name: control2_backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8080"

  frontend:
    build: ./gestion-tareas-frontend
    container_name: control2_frontend
    depends_on:
      - backend
    ports:
      - "5173:80"
